### ISSUE TITLE
[Bug]: Redis Sentinel - Request Timeout. POST /api/instance/sentinel-masters

### ISSUE THREAD

**Issue by ToshY** [redis/RedisInsight#1083]
I'm having issues when trying to connect to Redis Sentinel for the first time.

**Preconditions** (Any important steps we need to know)

- RedisInsight-v2 2.8.0 installed on main (Windows 10) machine, trying to connect to Redis Sentinel inside virtual machine (no firewall), which is setup with docker compose v2.
- Configuration of 1 master, 2 slaves and 3 sentinels.

**Steps to reproduce** (How to reproduce what you found step by step)

With docker compose I've setup a configuration consisting of 1 master, 2 slaves and 3 sentinels. Here's my partial configuration for `docker-compose.yml`

```yaml
version: '3.9'

x-restart: &restart-stopped
  restart: unless-stopped

x-redis-build: &redis-build
  build:
    context: ./data/redis
    dockerfile: Dockerfile
    args:
      REDIS_IMAGE_VERSION: ${REDIS_IMAGE_VERSION}

x-redis-volume: &redis-volume
  volumes:
    - redis:/data
    - redis_config:/usr/local/etc/redis

x-sentinel-volume: &sentinel-volume
  volumes:
    - redis_sentinel_config:/usr/local/etc/sentinel

x-sentinel-build: &sentinel-build
  build:
    context: ./data/sentinel
    dockerfile: Dockerfile
    args:
      REDIS_IMAGE_VERSION: ${REDIS_IMAGE_VERSION}
      REDIS_MASTER_NAME: ${REDIS_MASTER_NAME:-redismaster}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDISCLI_AUTH: ${REDIS_PASSWORD}
      REDIS_SENTINEL_QUORUM: ${REDIS_SENTINEL_QUOROM:-1}
      REDIS_SENTINEL_DOWN_AFTER: ${REDIS_SENTINEL_DOWN_AFTER:-3000}
      REDIS_SENTINEL_FAILOVER: ${REDIS_SENTINEL_FAILOVER:-6000}

x-redis-sentinel-environment: &redis-sentinel-environment
  environment:
    REDISCLI_AUTH: ${REDIS_PASSWORD}

x-redis-sentinel-network: &redis-sentinel-network
  networks:
    - redis-sentinel

x-redis-depends-master: &redis-depends-master
  depends_on:
    - redis-master

services:
  redis-master:
    <<: *redis-build
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass ${REDIS_PASSWORD}
    <<: *restart-stopped
    <<: *redis-sentinel-environment
    ports:
      - "6380:6379"
    <<: *redis-volume
    <<: *redis-sentinel-network

  redis-slave:
    <<: *redis-build
    command: redis-server /usr/local/etc/redis/redis.conf --slaveof redis-master 6379 --masterauth ${REDIS_PASSWORD}
    <<: *restart-stopped
    <<: *redis-depends-master
    <<: *redis-sentinel-environment
    ports:
      - "6381-6382:6379"
    <<: *redis-volume
    <<: *redis-sentinel-network

  redis-sentinel:
    <<: *sentinel-build
    <<: *restart-stopped
    <<: *redis-depends-master
    <<: *redis-sentinel-environment
    <<: *sentinel-volume
    <<: *redis-sentinel-network
    ports:
      - "26380-26382:26379"

  wait:
    image: waisbrot/wait
    environment:
      TARGETS: redis-master:6379 redis-slave:6379 redis-sentinel:26379
      TIMEOUT: 60
    networks:
      - redis-sentinel

volumes:
  redis:
    driver: local
  redis_config:
    driver: local
  redis_sentinel_config:
    driver: local

networks:
  redis-sentinel:
    driver: bridge
 ```

The following ports are open to outside: master port `6380`; slaves ports `6381`, `6382`; sentinels ports `26380`, `26381`, `26382`. I can access them just fine from outside (either with redis-cli or master/slaves with RedisInsight).

For the `sentinel` I'm using a custom Dockerfile which basically just replaces some placeholder variables names I had in the config.

```Dockerfile
ARG REDIS_IMAGE_VERSION=${REDIS_IMAGE_VERSION}

FROM redis:${REDIS_IMAGE_VERSION}

ARG REDIS_MASTER_NAME=${REDIS_MASTER_NAME}
ARG REDIS_PASSWORD=${REDIS_PASSWORD}
ARG REDIS_SENTINEL_QUORUM=${REDIS_SENTINEL_QUORUM}
ARG REDIS_SENTINEL_DOWN_AFTER=${REDIS_SENTINEL_DOWN_AFTER}
ARG REDIS_SENTINEL_FAILOVER=${REDIS_SENTINEL_FAILOVER}

COPY --chown=redis:redis ./config/sentinel.conf /usr/local/etc/sentinel/sentinel.conf

RUN sed -i -e "s:\$REDIS_MASTER_NAME:$REDIS_MASTER_NAME:g" \
    -e "s:\$REDIS_PASSWORD:$REDIS_PASSWORD:g" \
    -e "s:\$SENTINEL_QUORUM:$REDIS_SENTINEL_QUORUM:g" \
    -e "s:\$SENTINEL_DOWN_AFTER:$REDIS_SENTINEL_DOWN_AFTER:g" \
    -e "s:\$SENTINEL_FAILOVER:$REDIS_SENTINEL_FAILOVER:g" \
    /usr/local/etc/sentinel/sentinel.conf

EXPOSE 26379

CMD ["redis-server", "/usr/local/etc/sentinel/sentinel.conf", "--sentinel"]
```

This will create the following (parsed) `sentinel.conf`:

```
port 26379
dir /tmp
requirepass <redacted>
sentinel resolve-hostnames yes
sentinel monitor redismaster redis-master 6379 1
sentinel auth-pass redismaster <redacted>
sentinel down-after-milliseconds redismaster 2000
sentinel parallel-syncs redismaster 1
sentinel failover-timeout redismaster 4000
sentinel deny-scripts-reconfig yes
syslog-enabled yes
protected-mode no
```

For the master/slaves, I have a custom Dockerfile which just copies the config to the container.

```Dockerfile
ARG REDIS_IMAGE_VERSION=${REDIS_IMAGE_VERSION}

FROM redis:${REDIS_IMAGE_VERSION}

ARG REDIS_PASSWORD=${REDIS_PASSWORD}

COPY --chown=redis:redis ./config/redis.conf /usr/local/etc/redis/redis.conf

EXPOSE 6379
```

And my `redis.conf` for master/slave:

```
appendonly yes
maxmemory 100mb
maxmemory-policy allkeys-lru
enable-debug-command yes
```

Example of environment variables used (available from `.env` file):

```txt
###> Image versions ###
REDIS_IMAGE_VERSION="7.0-alpine"
###< Image versions ###

###> Redis sentinel ###
REDIS_MASTER_NAME="redismaster"
REDIS_PASSWORD="<redacted>"
REDIS_SENTINEL_QUOROM="1"
REDIS_SENTINEL_DOWN_AFTER="2000"
REDIS_SENTINEL_FAILOVER="4000"
###< Redis sentinel ###
```

**Actual behavior** (A short description of what you found)

Wanted to add my Sentinel to RedisInsight.

1. Click the "Add Redis Database"
2. Select "Autodiscover Databases"
3. Choose connect to "Redis Sentinel" and fill in the needed details
4. Click on "Discover database"
5. Now seeing a list of primary groups, I see my group `redismaster`.
6. I select the primary group `redismaster` and fill in the details.
7. I click on the "Add Primary Group".
8. Error message: `The connection has timed out, please check the connection details`.

**Expected behavior** (A short description of what you expected to find)

Succesfully connecting to the database.

**Screenshots** (Paste or drag-and-drop a screenshot or a link to a recording)

_Discover works_
![image](https://user-images.githubusercontent.com/31921460/186962201-36f6ac51-7344-4767-a2a0-733f6c5392c8.png)

_Adding primary group fails_
![image](https://user-images.githubusercontent.com/31921460/186962444-fb293300-fbda-4caf-9263-c209b56092f2.png)

**Additional context** (Operating system, version of RedisInsight, Redis database version, Redis module version, database type, connection type, logs, or any other information)

_Logs_
```
26/08/2022, 19:24:37 | INFO | InstancesBusinessService | Adding Sentinel masters. | {"stack":[]}
26/08/2022, 19:24:37 | INFO | RedisService | Successfully connected to the redis database | {"stack":[]}
26/08/2022, 19:24:37 | INFO | InstancesBusinessService | Adding oss sentinel. | {"stack":[]}
26/08/2022, 19:24:37 | INFO | RedisSentinelBusinessService | Getting sentinel masters. | {"stack":[]}
26/08/2022, 19:24:37 | INFO | RedisSentinelBusinessService | Getting a list of sentinel instances for master. | {"stack":[]}
26/08/2022, 19:24:37 | INFO | RedisSentinelBusinessService | Succeed to get a list of sentinel instances for master. | {"stack":[]}
26/08/2022, 19:24:37 | INFO | RedisSentinelBusinessService | Succeed to get sentinel masters. | {"stack":[]}
26/08/2022, 19:24:47 | ERROR | TimeoutInterceptor | Request Timeout. POST /api/instance/sentinel-masters | {"stack":[{}]}
26/08/2022, 19:24:47 | ERROR | RedisService | Failed connection to the redis oss sentinel | {"stack":[{"message":"connect ETIMEDOUT"}]}
26/08/2022, 19:24:47 | ERROR | InstancesBusinessService | Failed to add oss sentinel. | {"stack":[{"message":"connect ETIMEDOUT"}]}
26/08/2022, 19:24:47 | INFO | SettingsOnPremiseService | Getting application settings. | {"stack":[]}
26/08/2022, 19:24:47 | INFO | SettingsOnPremiseService | Succeed to get application settings. | {"stack":[]}
```

_OS_
Windows 10

_RedisInsight-v2_
2.8.0

_Redis version_
7.0-alpine (docker image; docker compose v2.10.0)
